# Generated by Django 3.1.3 on 2020-11-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20201104_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='logo',
        ),
        migrations.AddField(
            model_name='airline',
            name='logo_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
