# Generated by Django 3.1.3 on 2020-11-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20201104_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='eng_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
