# Generated by Django 3.1.3 on 2020-11-04 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_airline_eng_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_weekday',
        ),
        migrations.AddField(
            model_name='flightweekday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightweekday',
            name='weekday',
            field=models.CharField(max_length=45),
        ),
    ]
