# Generated by Django 3.1.3 on 2020-11-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20201104_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='remain_seats',
            field=models.IntegerField(default=0),
        ),
    ]
