# Generated by Django 3.1.2 on 2020-11-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('hotel', '0006_auto_20201104_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'hotel_bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('mobile', models.CharField(max_length=100)),
                ('total_people', models.IntegerField()),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.hotelbooking')),
            ],
            options={
                'db_table': 'booking_infos',
            },
        ),
    ]
