# Generated by Django 3.1.2 on 2020-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
