# Generated by Django 3.1.2 on 2020-11-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.AlterModelTable(
            name='hotelconvenience',
            table='hotel_conveniences',
        ),
        migrations.CreateModel(
            name='HotelTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.theme')),
            ],
            options={
                'db_table': 'hotel_themes',
            },
        ),
    ]
