# Generated by Django 3.1.2 on 2020-11-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20201104_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelimage',
            table='hotel_images',
        ),
        migrations.AlterModelTable(
            name='hoteloption',
            table='hotel_options',
        ),
    ]
