# Generated by Django 3.1.2 on 2020-11-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20201104_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteloption',
            old_name='addtional_price',
            new_name='additional_price',
        ),
    ]
