# Generated by Django 3.1.2 on 2020-11-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20201104_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenience',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='image',
        ),
        migrations.AddField(
            model_name='convenience',
            name='hotel',
            field=models.ManyToManyField(through='hotel.HotelConvenience', to='hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='convenience',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='option',
            name='hotel',
            field=models.ManyToManyField(through='hotel.HotelOption', to='hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hotel',
            field=models.ManyToManyField(through='hotel.HotelTheme', to='hotel.Hotel'),
        ),
    ]
