# Generated by Django 3.1.3 on 2020-11-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_people', models.IntegerField()),
                ('end_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_flight', to='flight.flight')),
                ('start_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_flight', to='flight.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'flight_booking_info',
            },
        ),
    ]
