# Generated by Django 3.1.2 on 2020-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250, null=True)),
                ('location_is_agreed', models.BooleanField()),
                ('promotion_is_agreed', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
