# Generated by Django 3.1.2 on 2020-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
